function createfigure(Y1)
%CREATEFIGURE(Y1)
%  Y1:  stem y

%  Auto-generated by MATLAB on 12-Nov-2013 20:17:31

% Create figure
figure1 = figure('PaperSize',[20.98 29.68]);

% Create axes
axes('Parent',figure1,'YTick',[0 1 2 3 4]);
box('on');
hold('all');

% Create stem
stem(Y1,'MarkerSize',20,'Marker','.','LineWidth',2);

